schema_version = 1
id = "TNDM-NSRN79"
title = "Clean up unused features in supi-flow plugin"

type = "chore"
priority = "p2"

depends_on = []
tags = ["flow:done", "flow:planned"]
[[documents]]
name = "archive"
path = "archive.md"
[[documents]]
name = "content"
path = "content.md"
[[documents]]
name = "plan"
path = "plan.md"
