name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
        with:
          experimental: true

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2.8.2

      - name: Format
        run: mise run fmt

      - name: Compile
        run: mise run compile

      - name: Clippy
        run: mise run clippy

      - name: Test
        run: mise run test
