name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        with:
          experimental: true

      - name: Install Rust toolchain
        run: rustup toolchain install --no-self-update

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Verify mise.lock is up to date
        run: |
          mise lock
          git diff --exit-code -- mise.lock

      - name: Format
        run: mise run fmt

      - name: Compile
        run: mise run compile

      - name: Architecture
        run: mise run arch

      - name: Clippy
        run: mise run clippy

      - name: Test
        run: mise run test
